/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TokenSecretName = string;
export type AdminChatId = number;
export type MessageLogToAdminChat = boolean;
export type ForceCategorySelection = boolean;
export type HashtagsInAdminChat = boolean;
export type HashtagMessageRarerThan = string;
export type EntrypointId = string;
export type Command = string;
export type NextBlockId = string;
export type Entrypoints = UserFlowEntryPointConfig[];
export type BlockId = string;
export type MessageText = string;
export type NextBlockId1 = string | null;
export type Blocks = UserFlowBlockConfig[];
export type X = number;
export type Y = number;

export interface BotConfig {
  token_secret_name: TokenSecretName;
  feedback_handler_config: FeedbackHandlerConfig | null;
  user_flow_config: UserFlowConfig | null;
  [k: string]: unknown;
}
export interface FeedbackHandlerConfig {
  admin_chat_id: AdminChatId;
  message_log_to_admin_chat: MessageLogToAdminChat;
  force_category_selection: ForceCategorySelection;
  hashtags_in_admin_chat: HashtagsInAdminChat;
  hashtag_message_rarer_than: HashtagMessageRarerThan;
  [k: string]: unknown;
}
export interface UserFlowConfig {
  entrypoints: Entrypoints;
  blocks: Blocks;
  node_display_coords: NodeDisplayCoords;
  [k: string]: unknown;
}
export interface UserFlowEntryPointConfig {
  command: CommandEntryPoint | null;
  [k: string]: unknown;
}
export interface CommandEntryPoint {
  entrypoint_id: EntrypointId;
  command: Command;
  next_block_id: NextBlockId;
  [k: string]: unknown;
}
export interface UserFlowBlockConfig {
  message: MessageBlock | null;
  [k: string]: unknown;
}
/**
 * Simplest user flow block: send message and immediately continue to the next block
 */
export interface MessageBlock {
  block_id: BlockId;
  message_text: MessageText;
  next_block_id: NextBlockId1;
  [k: string]: unknown;
}
export interface NodeDisplayCoords {
  [k: string]: UserFlowNodePosition;
}
export interface UserFlowNodePosition {
  x: X;
  y: Y;
  [k: string]: unknown;
}
